### ISSUE TITLE
What is this client

### ISSUE THREAD

**Issue by playeur242** [RMCQAZ/KevinClient#7]
k so how do i use it?
what kind of client is that ? a haked client to bypass 1.8 server? or a anarchy client?

**Comment by RMCQAZ** [comment]
使用方法:在释放里找到最新的版本，下载带有"kevinClient"名字的压缩包，解压它然后将解压出的文件夹重命名为KevinClient，文件夹中应该包含"natives"文件夹和"KevinClient.jar"、"KevinClient.json"文件。
把文件夹放入启动器的versions文件夹然后在启动器里选择KevinClient然后启动，确保你关闭了启动器的"检查客户端完整性"。

**Comment by RMCQAZ** [comment]
这是一个黑客客户端，可以用来绕过1.8-1.17的服务器(内置夸版本)

**Comment by RMCQAZ** [comment]
释放里的configs压缩包是配置文件，里面的json文件可以放入"启动器文件夹/Kevin/config"文件夹中然后通过在KevinClient中输入命令".config load 配置名称"来加载配置。你可以使用".config list"查看已有配置。在把配置放入文件夹后使用".config reload"来重载配置。

**Comment by beitianstu** [comment]
https://github.com/RMCQAZ/KevinClient/releases/tag/2.2

**Comment by playeur242** [comment]
hmm alright i downloaded it and im able to run it but it seems that it doesnt create the folder Kevin.
im also unable to open the gui

**Comment by RMCQAZ** [comment]
确保你关闭了"检查客户端完整性"

**Comment by RMCQAZ** [comment]
如果一切正常，主界面应该有一个彩虹色字符串

**Comment by beitianstu** [comment]
You can try adding "- noverify" to JVM parameters

**Comment by beitianstu** [comment]
你可以试试在jvm参数上加上“-noverify”

**Comment by beitianstu** [comment]
重新替换一下客户端文件
Replace the client file again

**Comment by playeur242** [comment]
Humm when i run it, it just change the kevinclient.jar file in vanilla version of minecraft called kevinclient.jar

**Comment by playeur242** [comment]
im using tlauncher maybe thats why

**Comment by beitianstu** [comment]
I recommend you to use this launcher https://hmcl.huangyuhui.net/download/

**Comment by beitianstu** [comment]
![image](https://user-images.githubusercontent.com/112758008/188523303-fb6713c2-2919-4783-bb6e-edcae29f96f9.png)
![image](https://user-images.githubusercontent.com/112758008/188523359-a9ed04a4-f3a5-4752-ab0d-775389dddc8d.png)
![image](https://user-images.githubusercontent.com/112758008/188523394-972e818d-225e-4fec-8051-d1cd727c949f.png)

**Comment by beitianstu** [comment]
![image](https://user-images.githubusercontent.com/112758008/188523578-d6534482-1fb9-42f3-b163-227f0a1ca3e0.png)

**Comment by beitianstu** [comment]
No thanks
